In [16]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('Raw_Data/raw_data_2016_2021.db')
cur = conn.cursor()
data = cur.execute('select * from FINAL_TABLE')

# df column 만들기
columns = list(map(lambda x: x[0], data.description))
df = pd.DataFrame(data, columns=columns)
df

,YYYY,Q,상권_구분명,상권명,업종수,점포수,총_생활인구,총_직장인구,아파트_단지수,아파트_평균_시가,총매출
0,2016,3,골목상권,남현2길,12,35,117518,1,43,150933708,1.548088e+09
1,2016,2,골목상권,남현2길,34,90,176625,1,43,150933708,5.743737e+09
2,2019,2,전통시장,이문제일시장,12,24,26769,1,1,181333333,1.046696e+09
3,2019,2,전통시장,가리봉시장,11,71,168005,1,3,872833333,3.469965e+09
4,2019,2,전통시장,강남시장_동작,11,16,66516,1,1,53385714,5.582304e+08
...,...,...,...,...,...,...,...,...,...,...,...
28131,2016,3,발달상권,서울 강남구 강남역_1,13,110,1100216,135251,8,393259902,6.972660e+09
28132,2018,2,발달상권,서울 강남구 강남역_1,48,726,1118876,135689,5,384765100,6.516807e+10
28133,2018,3,발달상권,서울 강남구 강남역_1,13,127,1199409,135689,5,384765100,1.025883e+10
28134,2018,4,발달상권,서울 강남구 강남역_1,11,128,1123192,135689,5,384765100,1.148588e+10
28135,2016,1,발달상권,서울 강남구 강남역_1,61,880,746803,136304,8,393259902,6.176285e+10

In [17]:
df.sort_values(['상권명','YYYY','Q']).head(30)

,YYYY,Q,상권_구분명,상권명,업종수,점포수,총_생활인구,총_직장인구,아파트_단지수,아파트_평균_시가,총매출
5433,2016,1,골목상권,가로공원로58길,18,45,55480,95,6,98943519,9.239395e+08
5302,2016,2,골목상권,가로공원로58길,18,46,38228,93,6,98943519,9.242100e+08
5304,2016,3,골목상권,가로공원로58길,5,14,23904,93,6,98943519,1.258191e+08
4462,2016,4,골목상권,가로공원로58길,4,9,24574,79,6,98943519,2.211368e+08
4474,2017,1,골목상권,가로공원로58길,15,45,60266,79,6,102135802,9.211438e+08
4209,2017,2,골목상권,가로공원로58길,14,44,39680,75,6,102135802,1.043577e+09
4212,2017,3,골목상권,가로공원로58길,5,14,29043,75,6,102135802,1.314040e+08
4294,2017,4,골목상권,가로공원로58길,4,12,47112,76,6,102135802,1.319590e+08
4295,2018,1,골목상권,가로공원로58길,14,44,30938,76,9,100413580,9.504049e+08
4296,2018,2,골목상권,가로공원로58길,12,34,30299,76,9,100413580,9.900919e+08
4298,2018,3,골목상권,가로공원로58길,4,12,32289,76,9,100413580,1.391049e+08
4300,2018,4,골목상권,가로공원로58길,5,14,33702,76,9,100413580,1.739852e+08
4049,2019,1,골목상권,가로공원로58길,14,43,472032,72,9,100413580,7.824588e+08
6505,2019,2,골목상권,가로공원로58길,9,33,450352,113,9,100413580,6.124315e+08
6508,2019,3,골목상권,가로공원로58길,4,12,445316,113,9,100413580,5.433092e+07
5186,2019,4,골목상권,가로공원로58길,8,26,466500,91,9,100413580,4.622546e+08
5192,2020,1,골목상권,가로공원로58길,7,24,503463,91,7,108533333,4.411514e+08
5198,2020,2,골목상권,가로공원로58길,7,24,477752,91,7,108533333,5.056566e+08
5205,2020,3,골목상권,가로공원로58길,7,25,453683,91,7,108533333,5.435429e+08
5212,2020,4,골목상권,가로공원로58길,8,27,442907,91,7,108533333,5.958778e+08
5221,2021,1,골목상권,가로공원로58길,7,24,458120,91,7,108533333,5.307661e+08
5228,2021,2,골목상권,가로공원로58길,7,24,389326,91,8,115576515,5.213720e+08
1017,2016,1,골목상권,가로공원로76가길,45,123,132849,18,69,100706656,3.033119e+09
969,2016,2,골목상권,가로공원로76가길,42,115,126311,17,69,100706656,2.812106e+09
973,2016,3,골목상권,가로공원로76가길,15,38,114554,17,69,100706656,9.522158e+08
1464,2016,4,골목상권,가로공원로76가길,6,10,95809,26,69,100706656,2.054630e+08
1470,2017,1,골목상권,가로공원로76가길,46,113,143212,26,70,110840745,3.259604e+09
1573,2017,2,골목상권,가로공원로76가길,38,96,146761,28,70,110840745,2.610314e+09
1580,2017,3,골목상권,가로공원로76가길,16,39,122248,28,70,110840745,1.019745e+09
1375,2017,4,골목상권,가로공원로76가길,16,40,121488,24,70,110840745,9.154406e+08

In [9]:
from sklearn.linear_model import RidgeCV
from sklearn.preprocessing import PolynomialFeatures
import numpy as np
from category_encoders import OneHotEncoder


def RidgeCVRegression(degree=3, **kwargs):
    return make_pipeline(PolynomialFeatures(degree), RidgeCV(**kwargs))

def prepro():
    return make_pipeline()

alphas = np.arange(0.01, 0.2, 0.01)

model = RidgeCVRegression(alphas=alphas, normalize=True, cv=5)
model.fit(X_train, y_train)
y_pred = model.predict(X_val)

In [10]:
preprocessing = make_pipeline(OneHotEncoder(), SimpleImputer())

YYYY         0
Q            0
상권_구분명       0
상권명          0
업종수          0
점포수          0
총_생활인구       0
총_직장인구       0
아파트_단지수      0
아파트_평균_시가    0
총매출          0
dtype: int64

In [14]:
pip install sklearn
from category_encoders import OneHotEncoder
x = [('a',5), ('b',6), ('a',3), ('c',1)]
y = [('b',3)]
encoded = OneHotEncoder.fit_transfomr(x)
encoded

SyntaxError: invalid syntax (<ipython-input-14-9fffb56372f9>, line 1)

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: DA96-0DC9

 C:\Users\jiho kang\OneDrive - 국민대학교\코드스테이츠\Section3\district_sales 디렉터리

2021-10-11  오후 03:36    <DIR>          .
2021-10-11  오후 03:36    <DIR>          ..
2021-10-11  오후 03:33    <DIR>          .ipynb_checkpoints
2021-10-11  오후 03:36            31,305 model.ipynb
2021-10-11  오후 03:32    <DIR>          Raw_Data
2021-10-07  오후 01:50                26 README.md
               2개 파일              31,331 바이트
               4개 디렉터리  139,098,411,008 바이트 남음